dist: trusty
language: python
python:
  - "3.6"
services:
  - docker
cache:
  directories:
    - /tmp/sc-docker
before_script:
  - python3 setup.py bdist_wheel
  - pip3 install dist/scbw*.whl
  - '[ -f /tmp/sc-docker/starcraft.zip ] && cp /tmp/sc-docker/starcraft.zip scbw/local_docker && echo "Using cached starcraft.zip" || true'
  - cp tests/*.dockerfile docker/dockerfiles
  - pushd docker
  - ./build_images.sh
  - popd
  - "[ -f /tmp/sc-docker/starcraft.zip ] || cp scbw/local_docker/starcraft.zip /tmp/sc-docker/starcraft.zip"
  - scbw.play --install
script:
  - scbw.play --headless --bots krasi0 'Marine Hell' --timeout 180 --docker_image starcraft:game 2>&1 | grep 'Winner is BotPlayer:krasi0:T' || (cat $HOME/.scbw/games/*/logs_0/* && false)
